# Woche 2: Einführung: Die Vormachtstellung Jesu Christi {#woche02}

```{block, type='rmdbible'}
 **Lese Hebräer 1,1-4**
```

## Bedeutung des Abschnittes

Die Anfangsverse des Hebräerbrief stellen Jesus als die letzte und endgültige Offenbarung Gottes an die Menschheit dar. Der Autor stellt zunächst fest, dass Gott "in vergangenen Zeiten vielfältig und auf vielerlei Weise" zu seinem Volk gesprochen hat (Hebr 1,1). Aber jetzt, in diesen letzten Tagen, hat Gott endgültig durch Jesus gesprochen -- durch seinen geliebten Sohn, den Schöpfer, Erhalter und Retter der Welt (Hebr 1,2-3) und ein genaues Bild des Vaters (Hebr 1,3). Die Grösse Jesu wird schliesslich durch seine Erhöhung zur Rechten Gottes über alle irdischen und himmlischen Wesen dargestellt (Hebr 1,4).

## Das Gesamtbild

Hebräer 1,1-4 fördert unsere Herzen zur Anbetung im Licht der strahlenden Majestät und unvergleichlichen Kraft Jesu Christi auf.

## Reflexion und Diskussion

Lesen Sie den Studienabschnitt, Hebräer 1,1-4, durch. Nachdem Sie den Abschnitt gelesen haben, lesen Sie den Abschnitt wieder und halten Sie Ihre eigenen Antworten auf die folgenden Fragen fest -- zuerst in Bezug auf Jesus als göttliche Offenbarung (Hebr. 1,1-2a), dann in Bezug auf Jesu Person, Werk und Status (Hebr. 1,2b-4).

### 1. Jesus als göttliche Offenbarung (Hebr. 1,1-2a)

Gott hat gesprochen. In den einleitenden Versen des Hebräerbriefes fegt der Autor über die Spanne von Gottes fortschreitender Offenbarung und landet auf Jesus Christus als Höhepunkt seiner Kommunikation. *Wenn man einige der wundersamen Weisen betrachtet, auf die Gott im Alten Testament zu den Patriarchen und Propheten gesprochen hat, was versucht der Autor zu zeigen, indem er kontrastiert, wie Gott zuvor gesprochen hat und wie Gott durch seinen Sohn nun endgültig zu seinem Volk gesprochen hat (Hebr 1,1-2)?*

In Hebräer 1,1-2 stellt der Autor des Hebräerbriefes die Offenbarung im Alten Testament der Endgültigkeit der Offenbarung Gottes in Jesus Christus in vier Bereichen gegenüber. *Vergleichen Sie die Epochen, Empfänger, und Agenten der Offenbarung sowie die Art und Weise, wie die Offenbarung ausgedrückt wurde.*

Jesus ist die endgültige Offenbarung Gottes in der Geschichte. Diese Wahrheit impliziert, dass die Offenbarung Gottes im Alten Testament für diese Epoche ausreichend, aber unvollständig war. *Wie wirkt sich die Offenbarung Jesu "in diesen letzten Tagen" darauf aus, wie wir den vollständigen Kanon der Schrift lesen (Lukas 24,27; Johannes 5,39-40)?*

### 2. Jesus: Person, Arbeit und Status (Hebr. 1,2b-4)

Viele Gelehrte glauben, dass die Titel "Sohn" und "Erbe", die in Hebräer 1,2 auf Jesus angewandt werden, auf Psalm 2,7-8 anspielen, einen königlichen Krönungspsalm, der an Gottes Versprechen an Davids Erben in 2 Samuel 7,12-16 erinnert. Im alten Israel war es der erstgeborene Sohn, der das Recht auf das Erbe hatte. Aufgrund seiner königlichen Sohnschaft ist Jesus der Erbe des Universums, einschliesslich der zukünftigen Welt (Hebr. 2,5-9), was eine Position des Segens und der Ehre ist. *Was hebt der Autor in der einzigartigen Beziehung und Verantwortung Jesu in Bezug auf das Universum hervor?*

In Hebräer 1,2-3 behauptet der Autor, dass die gesamte Schöpfung Gottes Jesus gehört, weil durch seine Vermittlung alle Dinge entstanden sind und das Universum durch seine Macht aufrechterhalten wird. Die Präexistenz, Autorität, Macht und volle Gottheit Jesu sind in seiner Rolle bei der Erschaffung und Aufrechterhaltung des Universums offensichtlich (Hebräer 1,10; siehe Johannes 1,3; 1 Korinther 8,6; Kol 1,16). *Was vermitteln uns diese Wahrheiten über den Zweck der Schöpfung und die Herrschaft Jesu über sein Werk?*

In Hebräer 1,3 wird Jesus als "Ausstrahlung der Herrlichkeit Gottes" beschrieben. In der biblischen Literatur bezieht sich "Herrlichkeit" oft auf die leuchtende Manifestation der Person Gottes (siehe 2. Mose 16,7; 33,18; Jes. 40,5; 60,1; 60,19). Was die Bedeutung des Wortes "Glanz" betrifft, so haben viele festgestellt, dass der Mond Licht reflektiert, während die Sonne Licht ausstrahlt, weil sie seine Quelle ist. *Was sagt uns das über Jesus als die Ausstrahlung Gottes und unsere Rolle als Reflektoren der Herrlichkeit Gottes?*

In Hebräer 1,3 wird verkündet, dass Jesus "der genaue Abdruck von Gottes Natur" ist. Für die ersten Leser hätte diese Sprache an einen Eindruck erinnert, der als Bild, wie auf einer Münze, angebracht wurde. Einfach ausgedrückt: Jesus ist das wahre Abbild Gottes (2 Kor 4,4; Kol 1,15). *Wie helfen uns diese Worte, das zu verstehen, was Jesus in Johannes 14,8-11 lehrte?*

Nachdem er sich für die Sünden gereinigt hatte, setzte sich Jesus "zur rechten Hand Gottes". Viele Gelehrte glauben, dass dies eine offene Anspielung auf Psalm 110,1 ist. Dieser Psalm wird direkt in Hebräer 1,13 zitiert und in Hebräer 8,1; 10,12; 12,2 angedeutet. *Was wird mitgeteilt, wenn der Autor schreibt, dass Christus "zur Rechten Gottes gesessen hat"?*

Jesus wird nicht nur den Propheten, sondern auch den Engeln wegen seines vorzüglicheren geerbten Namens für überlegen erklärt (Hebr. 1,4). Der Autor scheint 2. Samuel 7 in Bezug auf die Ehre, die Jesus als Davidischer Erbe zuteil wurde, zu wiederholen. *Welche Bedeutung hat es, Jesus in der Position des königlichen Erben von den Engeln zu unterscheiden?*

```{block, type='rmddefinition'}
**Engel -- Definition**

Ein übernatürlicher Gesandter Gottes, oft gesandt, um seinen Willen zu erfüllen oder den Menschen bei der Erfüllung seines Willens zu helfen. Obwohl Engel mächtiger sind als Menschen und oft Ehrfurcht einflössen, sollen sie nicht angebetet werden (Kol. 2,18; Offb. 22,8-9). In der Bibel gibt es jedoch verschiedene Erscheinungen eines "Engels des Herrn", der offenbar eine physische Manifestation Gottes selbst ist.

```


Lesen Sie die folgenden drei Abschnitte zu den Themen "Einblicke in das Evangelium", "biblische Zusammenhänge" und "theologische Vertiefungen". Nehmen Sie sich dann Zeit, über die persönlichen Auswirkungen nachzudenken, die diese Abschnitte auf Ihren Weg mit dem Herrn haben können.

## Einblicke in das Evangelium

**REINIGUNG DER SÜNDE.** Die Bibel macht deutlich, dass die Sünde und ihre Verderbnis zerstörerische Auswirkungen auf die Menschheit und die gesamte Schöpfung haben. Die Notwendigkeit der Reinigung von der Sünde ist Teil der übergreifenden Handlung der Bibel. Das kosmische Ausmass der Sünde bildet die Grundlage für die kosmische Erlösung durch den Sühnetod Jesu. Im Alten Testament wurden Sühneopfer für das Volk Gottes eingeführt, um die Strafe für seine Sünde zu vermitteln und die Reinigung durch Blut zu erlangen (Levitikus 16). Sühneopfer reinigten auch die Gegenstände des irdischen Tempels, der dem Kosmos nachempfunden ist, der Tempelbehausung Gottes. Im Hebräerbrief sehen wir, dass der Tod Jesu die notwendige Reinigung von Sünden und die Reinigung des menschlichen Gewissens vor Gott erlangte (Hebr. 1,3; 9,14). Das Opfer Jesu erstreckte sich auch auf die Reinigung "himmlischer Dinge" (Hebr. 9,23) und ist daher kosmisch. Das Herzstück des Evangeliums ist die gute Nachricht, dass das Blut Jesu für die Sünde gesühnt hat und Auswirkungen auf den gesamten Kosmos hat.

**DIE VOLLSTÄNDIGE ERRETTUNG.** Kurz bevor Jesus seinen letzten Atemzug am Kreuz tat, verkündete er: "Es ist vollbracht" (Johannes 19,30). Das Werk, zu dessen Vollendung der Vater ihn gesandt hatte, war vollendet -- sein vollkommenes Opfer für unsere Sünde war vollendet (Hebr. 1,3; 9,11-12, 25-28). Der Verfasser des Hebräerbriefes weist darauf hin, dass sich Jesus, nachdem sein Werk am Kreuz und in der Auferstehung vollendet war, zur rechten Hand Gottes setzte und damit die Endgültigkeit seines Werkes und seines Status unterstrich. Im Gegensatz zu den levitischen Priestern, die Jahr für Jahr unvollkommene Opfer brachten, um die Sünden zu verdecken, brachte Jesus das perfekte Einwegopfer dar, das die Sünde auslöschte -- und dann nahm er seinen Platz ein, um für immer zu regieren (Hebr 10,11-12).


```{block, type='rmddefinition'}
**Sünde -- Definition**

Jede Verletzung oder Nichtbeachtung der Gebote Gottes oder der Wunsch, dies zu tun.
```


## Biblische Zusammenhänge

**OFFENBARUNG UND ERLÖSUNG.** Offenbarung in menschlicher Sprache ist wesentlich für die Vermittlung von Gottes Erlösungsplan durch Jesus Christus. Ohne verbale Offenbarung kann die Menschheit keinen Zugang zu der guten Nachricht von Gottes Erlösung haben. Die Offenbarung im Alten Testament steht jedoch nicht für sich allein, sie ist unvollständig ohne ihren Abschluss und ihre Erfüllung in Jesus Christus. "In diesen letzten Tagen" kommen wir zu der Erkenntnis, dass die Personen und Institutionen des Alten Testaments auf die Person und das Werk Jesu Christi hinweisen, in dem wir die Erlösung finden (Hebr 1,1-2).

**DEr VOLLKOMMENE SOHN.** In der Bibel wird Sohnschaft mit Familienähnlichkeit, Abstammung und Erbe in Verbindung gebracht. Nicht nur Gottes erster "Sohn" Adam wurde nach seinem Bilde geschaffen, Adam gebar auch Söhne nach seinem eigenen Bilde und damit nach dem Bilde Gottes (1. Mose 1,28; 5,1-3). Gott bezeichnet Israel später als seinen gemeinsamen "Sohn" (2. Mose 4,22-23; Ps 2,7; Hos 11,1) und seinen "Erstgeborenen" (5. Mose 33,17; Ps 2,7; Jer 31,9; Esra 6,58). Sowohl Adam als auch Israel waren nicht das, was der Vater wollte. Beide taten nicht, was Gott von ihnen als "Söhne" verlangt hatte. Ihr Ungehorsam steht in krassem Gegensatz zu dem makellosen Gehorsam Jesu, des göttlich-menschlichen Sohnes, der den Vater vollkommen nachbildet und ihm Ehre bringt (Spr 10,1; 15,20; 23,15).

**DIE HERRLICHKEIT GOTTES.** In der biblischen Sprache ist die Herrlichkeit Gottes ein Abbild seiner Vollkommenheit, Schönheit und Grösse. Mose 1,27 wird uns gesagt, dass Adam als Gottes Ebenbild geschaffen wurde. Als Gottes Bildträger wurde Adam -- zusammen mit dem Rest der Menschheit -- geschaffen, um Gottes Herrlichkeit widerzuspiegeln. Aber die Sünde zerstörte die reine Widerspiegelung der Herrlichkeit Gottes in Adam und seinen Kindern. Von der Sünde unvermindert wird Jesus als der zweite und letzte Adam erklärt, der Gottes Ebenbild vollständig repräsentiert und seine Herrlichkeit makellos ausstrahlt (Römer 5,12-21). Doch im Gegensatz zu Adam ist Jesus die genaue Prägung Gottes und in der Substanz identisch mit Gott (Hebr. 1,3).

## Theologische Vertiefungen

**SCHÖPFUNG.** Die biblische Geschichte beginnt mit einer majestätischen Beschreibung, wie Gott Himmel und Erde zu seiner Behausung schuf und wie sie von seinen Geschöpfen bewohnt wurde. In Hebräer 1,2-3 wird uns gesagt, dass Jesus nicht nur das Instrument des ursprünglichen Schöpfungsaktes in 1. Mose 1 ist, sondern auch eng in die fortgesetzte Sorge für die Schöpfung eingebunden ist (vgl. die Beschreibung Jesu in Johannes 1,1-18). Jesus war der Akteur, in dem und durch den das gesamte Universum von Raum und Zeit entstand. Als das Abbild des menschgewordenen Gottes ist Jesus der Berührungspunkt zwischen dem Schöpfer und seinem Universum. Er ist der Bezugsrahmen für den ursprünglichen Zweck und für die Erneuerung der Schöpfung Gottes nach dem Fall (Kol. 1,15-23).

**VORSEHUNG.** Die Vorsehungslehre lehrt, dass Gott die von ihm geschaffene Welt erhält und sie zu den von ihm festgelegten Zielen führt. In Hebräer 1,3 sehen wir, dass Gott persönlich an seiner Schöpfung beteiligt ist, um sie zu erhalten und zu bewahren. Seine providentielle Herrschaft erstreckt sich über alle Dinge im Universum; die gesamte Schöpfung wird durch das mächtige Wort Jesu erhalten und weitergeführt. Darüber hinaus kam Jesus, um die endgültige und vollständige Reinigung für die Sünden zu gewährleisten.

## Persönliche Anwendung

Nehmen Sie sich Zeit, über die Auswirkungen von Hebräer 1,1-4 auf Ihr eigenes Leben nachzudenken. Beachten Sie die persönlichen Implikationen für Ihren Weg mit dem Herrn im Licht der (1) Einblicke in das Evangelium, (2) biblische Zusammenhänge, (3) theologischen Vertiefungen und (4) dieses Abschnitts als Ganzes.

1. Einblicke in das Evangelium
2. Biblische Zusammenhänge
3. Theologische Vertiefungen
4. Hebräer 1,1-4


## Wenn Sie diese Einheit abschliessen . . .

Nehmen Sie sich jetzt einen Moment Zeit, um um den Segen und die Hilfe des Herrn zu bitten, während Sie das Studium des Hebräerbriefes fortsetzen. Und nehmen Sie sich auch einen Moment Zeit, auf diese Studieneinheit zurückzublicken, über einige Dinge nachzudenken, die der Herr Sie vielleicht lehrt, und Dinge zu notieren, die Sie in Zukunft nachschauen sollten.

***

Nur für private Zwecke. Übersetzt aus dem Englischen von eurem Diener

Hebrews: A 12-Week Study $\copyright$ 2015 by Matthew Z. Capps. All rights reserved.

[source](https://www.thegospelcoalition.org/course/knowing-bible-hebrews/#week-2-introduction-the-supremacy-of-jesus-christ-heb-11-4)
