# Woche 3:  Jesus ist den Engelswesen überlegen {#woche03}



## Der Ort der Passage

Durch eine Kette von alttestamentlichen Passagen wird Jesus als der einzige Sohn Gottes den Engeln überlegen gezeigt (Hebr. 1,5-14). Aufgrund seines Status als Sohn Gottes genießt Jesus eine einzigartige Beziehung zum Vater in Position, Wesen und Autorität. Jesus wird auch als der einzigartige Menschensohn dargestellt, was ihn als das wahre Opfer für die Sünde etabliert und ihn als den mitfühlenden Hohenpriester einführt (Hebr. 2,1-18). Dieser Abschnitt enthält die erste von fünf Warnungen im Buch der Hebräer; hier werden wir gewarnt, auf die durch Jesus Christus bereitgestellte Rettung zu vertrauen.

## Das Gesamtbild

Hebräer 1,5-2,18 erhebt Jesus über die Engel als den einzigartigen Sohn Gottes, der die Sünden der Menschheit versühnte und nun als Mittler und Hoherpriester zwischen Gott und der Menschheit dient.

```{block, type='definition'}
 **Sühne -- Definition**

Die Beschwichtigung des Zorns durch die Darbringung einer Gabe oder eines Opfers. Jesus versöhnte die Sünden der Menschheit durch sein Leiden und seinen Tod (Römer 3,25; Hebr 2,17; 1. Johannes 2,2; 4,10).
```


## Reflexion und Diskussion

Lesen Sie den gesamten Abschnitt für diese Studie, Hebräer 1:5-2:18. Nachdem Sie den gesamten Abschnitt gelesen haben, beginnen Sie damit, die aufgelisteten Teile erneut durchzulesen und Ihre eigenen Antworten auf die folgenden Fragen aufzuzeichnen. (Weitere Hintergrundinformationen finden Sie in der ESV-Studienbibel, Seiten 2361-2364, die online unter www.esvbible.org verfügbar ist).

### 1. Der Status Jesu als ewiger Sohn und König (Hebr. 1,5-14)

Der Autor unterstützt die Überlegenheit Jesu gegenüber den Engeln, indem er verschiedene Texte des Alten Testaments aneinander reiht, um seine Argumentation zu untermauern. Jesus wird durch die Art seiner Beziehung zum Vater (Hebr. 1,5), seine Stellung über die Engel (Hebr. 1,6-7) und seine königliche Autorität (Hebr. 1,8-9) als überlegen dargestellt. Wie stärkt die Anwendung alttestamentlicher Texte durch den Autor auf Jesu Sohnschaft (Ps. 2,7; 2 Sam. 7,14), seine Stellung (Ps. 97,7; 104,4) und seine Autorität (Ps. 45,6-7) unseren Glauben an Jesus heute?

Mit dem Zitat von Psalm 102,25-27 in Hebräer 1,10-12 betont der Autor die Rolle Jesu in der Schöpfung und seine ewige Natur. Wie stärken Jesu Rolle in der Schöpfung und seine ewige Herrschaft über die Schöpfung unsere Treue zu ihm?

In Hebräer 1,13 wendet der Autor Psalm 110,1 auf Jesus an und zeigt ihn als erhaben zur rechten Hand Gottes, eine Position des Vorrechts und der Macht (siehe Hebräer 1,3). Dieser spezielle Psalm bezieht sich auf die Inthronisierung des Königs und den Sieg über alle seine Feinde. Was vermittelt die Sitzhaltung Jesu über die Absichten Gottes im Leben, Tod und in der Auferstehung Christi?

Nach Hebräer 1,14 sind Engel dienende Geister, die die Aufgabe haben, denen zu dienen, die die Erlösung erben sollen. Wie spricht die Rolle der Engel zur Ehre des Evangeliums und zur Autorität von Jesus Christus?

### 2. Warnung Eins: Vor der Vernachlässigung der Errettung (Hebr. 2,1-4)

Der Autor untermauert die Verlässlichkeit des mosaischen Gesetzes dadurch, dass es von den Engeln gegeben wurde (Hebr. 2,2; siehe auch Deut. 33,2). Wenn das mosaische Gesetz mit einer Vergeltung für Ungehorsam kam, wie viel mehr werden dann diejenigen belohnt, die das von Gott dem Vater und Gott dem Sohn bezeugte und durch Zeichen, Wunder und Wundertaten bestätigte Heil ablehnen (Hebr. 2,3-4)? Warum sollten wir außerdem darauf achten, dass wir nicht vom Evangelium der Gnade abweichen und seine Anwendung auf unser Leben bewusst vernachlässigen (Hebr. 2,1)?

### 3. Jesus als der Gründer des Heils (Hebr. 2,5-18)

In Hebräer 2,5-9 heißt es, dass die gegenwärtige und die zukünftige Welt Jesus Christus unterworfen sind. Aber zum gegenwärtigen Zeitpunkt sehen die Gläubigen die höchste Herrschaft Jesu über den Kosmos nicht klar. Darüber hinaus sind die Menschen angesichts des Sündenfalls und des Versagens des Menschen, den Schöpfungsauftrag aufrechtzuerhalten, vorübergehend in ihrem Status und ihrer Autorität niedriger als die Engel (1. Mose 1,28). Wie erfüllt Jesus als der wahre Vertreter der Menschheit Gottes Gebot, alles in der Schöpfung unter die Herrschaft zu stellen (Hebr 2,8)?

In Hebräer 2,10-13 zitiert der Autor Psalm 22,22 und Jesaja 8,17b-18, um zu zeigen, dass die Nachfolger des einen einzigartigen Sohnes Gottes nun auch "Söhne" genannt werden, denn sie werden durch Jesu vollkommenes Leben und Opfer in die neu erlöste Menschheitsfamilie aufgenommen. Welche Vorteile hat es, ein Sohn Gottes oder ein Bruder Jesu Christi zu sein (siehe Gal 4,1-7)?

In Hebräer 2,14-18 sehen wir die Solidarität Jesu mit der Menschheit, indem er "Fleisch und Blut" annimmt. Doch im Gegensatz zu dem, was jeder andere Mensch hätte tun können, stürmte Jesus die Tore des Todes, besiegte den Bösen und befreite uns aus der Sklaverei bis zum Tod (Hebr. 2,14-16). Wie also gibt Hebräer 2,17-18 den Gläubigen inmitten geistlicher Gebrechen Hoffnung?

```{block, type='definition'}
**Gnade -- Definition**

Unverdiente Gunst, insbesondere die kostenlose Gabe der Erlösung, die Gott den Gläubigen durch den Glauben an Jesus Christus schenkt.
```


Lesen Sie die folgenden drei Abschnitte zu den Themen Evangeliums-Blicke, Ganz-Bibel-Verbindungen und Theologische Sondierungen. Nehmen Sie sich dann Zeit, über die persönlichen Auswirkungen nachzudenken, die diese Abschnitte für Ihren Weg mit dem Herrn haben können.

## Einblicke in das Evangelium

**ZUVERLÄSSIGES EVANGELIUM.** Die Gefahr, das Evangelium Jesu Christi zu vernachlässigen, wird durch seine Überlegenheit gegenüber der vorherigen Offenbarung, die durch Propheten und Engel kam, noch erhöht (Hebr. 1,2; 2,2). Verlässlichen Augenzeugen zufolge verkündete Jesus selbst zuerst seine gute Nachricht (Hebr. 2,3). Darüber hinaus bestätigte Gott diese von Jesus verkündete gute Nachricht mit Zeichen, Wundern, Wundertaten und Gaben des Heiligen Geistes (Apg 2,22; 2. Kor 12,12; Hebr 2,4). Das Evangelium ist nicht nur eine gute Nachricht; es ist eine verlässliche gute Nachricht - eine gute Nachricht, auf die es sich lohnt, unser Leben zu riskieren.

**DER GUTE KÖNIG.** Im ersten Jahrhundert wurde das "Evangelium" ("gute Nachricht") regelmäßig verwendet, um die Geburt, die Verkündigung, die Thronbesteigung oder den Sieg eines großen Königs zu bezeichnen. Nach Hebräer 1,8 ist Jesus der ewige messianische König, dessen Herrschaft nie enden wird. Im Gegensatz zu den davidischen Königen der Vergangenheit wird seine Herrschaft nicht durch Zerbrechlichkeit behindert. Die Herrschaft Jesu ist von vollkommener Gerechtigkeit und Rechtschaffenheit geprägt. Die königliche Herrschaft Jesu ist auch insofern gut, als er sein Volk befreit, heiligt und für es sorgt (Hebr. 1,8; 2,6; 9-18). Schließlich wird Jesus, anders als jeder andere König in der Geschichte, für immer und ewig als König der Könige regieren (Offb 5,9-14).

**TRANK TIEF AUS DEM TOD.** Als vollkommenes Opfer kostete Jesus den Tod für alle, die glauben (Hebr. 2,9). Mehr noch, Jesus trank den Kelch des Zornes Gottes bis zum bitteren Abschaum, um den Zorn Gottes für die Gläubigen zu verzehren und so den Todesgriff des Teufels zu zerstören (Hebr. 2,14-15, 17). In Christus gibt es keine Angst im Tod, sondern nur Hoffnung im Leben. Am Kreuz hat Jesus die Macht des Todes beseitigt. In seiner mächtigen Auferstehung besiegelte Jesus die Verheißung eines neuen ewigen Lebens.
Ganz-Bibel-Verbindungen

**VERWALTETER KÖNIG.** In Hebräer 1,5b greift der Autor die Verkündigung König Davids über seinen Bundeserben auf, den Gott als seinen eigenen Sohn einsetzen wird (2 Sam 7,14; 1 Chron 17,13). Im Zusammenhang mit 2 Samuel ist dies sicherlich Salomo. Während diese Worte in Salomo nie verwirklicht wurden, haben sie ihre Erfüllung in Jesus gefunden, der der wahre und größere Davidskönig ist, dessen Königreich für immer errichtet ist (2. Sam. 7,16). Daher findet die königliche Herrschaft, die die israelitischen Könige vorausgesagt haben - die aber nicht als Vertreter Gottes auf Erden aufrecht erhalten werden konnte - ihre Erfüllung in Jesus (Hebr. 2,8-9; Offb. 3,21). Die Könige des Alten Testaments sind die Schatten; Jesus ist die Substanz. Jesus ist der ewige König der Könige, dessen vollkommene Herrschaft und Gerechtigkeit niemals enden wird.

**DER GEISTLICHE EXODUS.** Der Autor des Hebräerbriefes bezeichnet Jesus nicht nur als den Gründer des Heils, sondern auch als denjenigen, der das Volk des neuen Bundes in die Herrlichkeit führt (Hebr. 2,10). Einige Bibelversionen übersetzen "Gründer" mit "Pionier". Die Symbolik von Jesus, der unsere Rettung vorbereitet hat, blickt im Alten Testament auf diejenigen zurück, die die Israeliten durch die Wüste und auch in die Schlacht geführt haben (Num. 10,4; 13,2-3; Jud. 5,15; 9,44; 11,6-11; 1 Chron. 5,24; 26,26; 2. Chron. 23,14; Neh. 2,9). Als Vorläufer und Vertreter seines Volkes ist Jesus in die Gegenwart Gottes eingetreten, um ihnen den Eintritt in die Gegenwart Gottes zu sichern; er ist der Weg geworden, auf dem sie in die verheißene Ruhe Gottes eintreten können. Jesus ist der wahre und größere Mose, der sein ganzes Volk in Gottes Ruhe erlöst.

**BESCHAFFUNG.** Das Wort "Versöhnung" vermittelt den Sinn eines Sühneopfers, das den Zorn Gottes gegen die Sünde befriedigt (Römer 3,25; Hebr 2,17). In der gesamten Erlösungsgeschichte wird Gottes gerechter Zorn als Notwendigkeit gezeigt, besänftigt zu werden, bevor die Sünde des Volkes Gottes vergeben werden kann. Die endgültige Versöhnung durch Christus, die ein für allemal den vollen Lohn für die Sünde bringt, wird im Alten Testament mehrmals angedeutet (Ex 32,11-14; Num 25,8; Josh 7,25-26). Wo die alttestamentlichen Opfer versagten, gelang es Jesus, Gottes Zorn ein für allemal gegen die Sünde seines Volkes zu versöhnen.

```{block, type='definition'}
**Erlösung -- Definition**

Befreiung von den ewigen Folgen der Sünde. Der Tod und die Auferstehung Jesu erkauften den Gläubigen ewige Erlösung (Römer 1,16).
```


## Theologische Sondierungen

**ANGELS.** Nach der Heiligen Schrift sind Engel majestätische, erschaffene Wesen, die in erster Linie als Anbeter und Boten Gottes fungieren, seinen Willen offenbaren und Schlüsselereignisse in der gesamten Erlösungsgeschichte ankündigen (Dan 9,20-27; Lukas 1,11-20; Apg 7,38; Hebr 2,2). Engel dienen auch dem Volk Gottes (1. Könige 19,5-7; Ps. 91,11; Hebr. 1,14). Die Pracht der Engel dient als Bezugspunkt, von dem aus der Autor der Hebräer von der viel höheren Stellung des erhabenen Sohnes sprechen kann (Hebr. 1,5-13). Die Anbetung Christi durch die Engel, wenn er in den Himmel kommt, festigt seine überragende Stellung (Hebr. 1,6). Obwohl Engel schöne und mächtige Wesen sind, übertrifft die Schönheit und Macht Christi die ihre exponentiell.

**MENSCHLICHKEIT JESU.** Während seiner Zeit auf der Erde wurde Jesus als der inkarnierte Gottmensch niedriger als die Engel gemacht, indem er voll an menschlichem Fleisch und Blut teilhatte (Hebr. 2,9.14). Die Menschlichkeit Christi war notwendig, damit er Versuchungen und Leiden ertragen und so als das einzige wahre Opfer für die Sünde dienen konnte. Wenn Jesus nicht in jeder Hinsicht (außer der Sünde) menschlich wurde und die ganze Bandbreite der Versuchung erfuhr, konnte er nicht als mitfühlender Hohepriester dienen, der die geistlichen Gebrechen der Menschen kennt.

**WUNDER.** In der Bibel sind Wunder Gottes nicht-normative Machttaten, durch die er von sich selbst Zeugnis ablegt und seine Boten und seine Botschaft beglaubigt (Johannes 2,11; 3,2; Apostelgeschichte 2,22). In der frühen Kirche vollbrachten die Apostel und andere ebenfalls Wunder, um die Gültigkeit der von ihnen verkündeten Evangeliumsbotschaft zu bestätigen (Apg 2,43; 3,6-10; 4,30; 8,6-8,13; 9,40-42). In Hebräer 2,3-4 lesen wir, dass Gott die Botschaft der Erlösung selbst durch Zeichen und Wunder bestätigt hat.

## Persönliche Implikationen

Nehmen Sie sich Zeit, über die Auswirkungen von Hebräer 1,5-2,18 auf Ihr eigenes Leben heute nachzudenken. Beachten Sie die persönlichen Implikationen für Ihren Weg mit dem Herrn im Licht der (1) Evangeliums-Blicke, (2) Gesamtbiblischen Zusammenhänge, (3) Theologischen Klänge und (4) dieses Abschnitts als Ganzes.

1. Einblicke in das Evangelium
2. Ganz-Bibel-Verbindungen
3. Theologische Sondierungen
4. Hebräer 1,5-2,18

## Wenn Sie diese Einheit abschliessen . . .

Nehmen Sie sich jetzt einen Moment Zeit, um den Segen und die Hilfe des Herrn zu erbitten, während Sie mit dem Studium der Hebräer fortfahren. Nehmen Sie sich auch einen Moment Zeit, um diese Studieneinheit noch einmal durchzugehen, über einige Dinge nachzudenken, die der Herr Sie vielleicht lehrt, und sich Dinge zu merken, die Sie in Zukunft noch einmal überprüfen sollten.

***

Nur für private Zwecke. Übersetzt aus dem Englischen von eurem Diener

Hebrews: A 12-Week Study © 2015 by Matthew Z. Capps. All rights reserved.

https://www.thegospelcoalition.org/course/knowing-bible-hebrews/#week-3-jesus-is-superior-to-angelic-beings-heb-15-218
