# Woche 4: Jesus ist Mose überlegen {#woche04}

```{block, type='biblebox'}
 **Lese Hebräer 3,1-4,13**
```

## Bedeutung des Abschnittes

In Hebräer 3,1-6 wird gezeigt, dass Jesus Moses, einem der treuesten Knechte Gottes, überlegen ist. Jesus ist der höchsten Ehre würdig, weil er der treue Hohepriester und Sohn Gottes ist. Der Autor ermahnt die Christen, mit Treue und Ausdauer auf Gottes Erlösungswerk zu antworten (Hebräer 3,7-4,13). In diesem Abschnitt erhalten die Leser ihre zweite Warnung, nämlich die, im Gegensatz zu den Menschen der Exodus-Generation, die ihre Herzen verhärtet haben, im Glauben auszuharren (Hebräer 3,7-18).

## Das Gesamtbild

Hebräer 3,1-4,13 zeigt Jesus Christus als den Apostel und vollkommenen Sohn, der gesandt wurde, um als treuer Hohepriester zu dienen.

## Reflexion und Diskussion

Lesen Sie den Studienabschnitt, Hebräer 3,1-4,13, durch. Nachdem Sie den Abschnitt gelesen haben, lesen Sie den Abschnitt wieder und halten Sie Ihre eigenen Antworten auf die folgenden Fragen fest. 

### 1. Jesus ist grösser als Moses (Hebräer 3,1-6)

In Hebräer 3,1-2 bekennt sich Jesus als der Apostel, der gesandt wurde, um Befreiung zu bringen, und als der Hohepriester, der die Sünden des Volkes Gottes sühnen soll. Was bedeutet es, als heilige Mitglieder der Familie Gottes "an einer himmlischen Berufung teilzuhaben" (Hebräer 3,1)? Wie kann die Treue Jesu uns ermutigen, im Vertrauen und in der Hoffnung an unserer himmlischen Berufung festzuhalten (Hebräer 3,6)?

Mose war ein treuer Knecht im Haus Gottes trotz der Treulosigkeit der Israeliten (Num 12,7). Aber Jesus ist wegen seiner vollkommenen Treue als der Sohn, der nicht nur dem Haus Gottes vorsteht, sondern es auch gebaut hat, einer grösseren Ehre würdig als Mose (1. Chron. 17,14-17; Hebräer 3,1-6). Welche Bedeutung hatte für die ursprüngliche Zuhörerschaft - die mit dem Alten Testament vertraut war - der Vergleich des Autors mit Jesus und Mose? Was können wir von der Treue des Mose als Mitglied des Hauses Gottes lernen?

### 2. Warnung Zwei: Das Versagen der Exodus-Generation (Hebräer 3,7-19)

Nachdem der Autor den Kontrast zwischen der Treue von Moses und Jesus untersucht hat, wendet er sich nun den Antworten ihrer Anhänger zu, indem er Psalm 95,7-11 zitiert. Der Autor warnt vor dem Unglauben eines sündigen, verhärteten Herzens, das einen zum Abfall veranlasst (Hebräer 3,7-12). Wie tragen diese starken Worte dazu bei, uns davon abzuhalten, in der Rebellion zu leben? Wie erleuchtet uns dieser Abschnitt über den Unterschied zwischen echtem und falschem Glauben?

In Hebräer 3,13-14 erklärt der Autor, wie gegenseitige Ermutigung und Rechenschaftspflicht das Gegenmittel gegen die Zersetzung des Unglaubens sein können. Wie hält die Befolgung der Ermahnung zu gegenseitiger Verpflichtung im Teilen Christi Christen dazu an, bis zum Ende durchzuhalten?

In Hebräer 3,15 kehrt der Autor zu Psalm 95,7-8 zurück und erinnert die Leser an die Misserfolge der Exodusgeneration (Hebräer 3,16-19; siehe Ex 17,1-7; Num 14,20-38). Wie weist der Unglaube der Exodus-Generation und ihr Versagen, in Gottes Ruhe zu gehen, sowohl auf die Warnung vor dem Abfall als auch auf die Hoffnung hin, die wir in Jesus Christus haben?

### 3. In Gottes Ruhe eintreten (Hebräer 4,1-13)

Gottes Befreiung der Israeliten und ihre Hoffnung, das verheissene Land zu betreten, war ein Vorzeichen für das Werk Jesu. Für die Kirche ist die verheissene Ruhe Gottes in der Auferstehung Christi eingeweiht worden und wartet auf die Vollendung bei seinem zweiten Kommen; aber der Autor fürchtet, dass einige nicht in diese Ruhe eintreten werden (Hebr 4,1). Wie verhält sich der Glaube nach Hebräer 4,1-3 dazu, in die verheissene Ruhe Gottes einzutreten?

In Hebräer 4,4 spricht der Autor von der Einkehr in Gottes Ruhe in Bezug auf den siebten Schöpfungstag (1. Mose 2,2) und stellt fest, dass die Israeliten es letztlich versäumt haben, in die Ruhe Gottes einzutreten (Hebräer 4,5-9). Zusammengenommen ist Gottes Sabbatruhe, die in Genesis 2 begann, immer noch offen und kann betreten werden. Was bedeutet es, in seine Werke einzutreten und von ihnen zu ruhen, wie Gott von seinen Werken (Hebräer 4,10)?

Nachdem der Autor die Leser aufgerufen hat, sich darum zu bemühen, in Beharrlichkeit in Gottes Ruhe einzutreten, erinnert er sie daran, dass treuloser Ungehorsam nicht unbemerkt bleiben wird (Hebräer 4,11-13). Wenn wir wissen, dass Gottes Wort wie ein Mittel wirkt, das die innersten Gedanken und Absichten offenbart, wie können wir dann sein Wort benutzen, um Ungehorsam und Unglauben zu bekämpfen?

```{block, type='definition'}
**Sabbat -- Definition**

Samstag, der siebte Tag der Woche, der jüdische Tag der Anbetung und der Ruhe (1. Mose 2,2-3; Ex 31,13-17). Christen treffen sich am Sonntag, dem Tag der Auferstehung Christi (Apg 20,7), zum Gottesdienst und betrachten den Sonntag statt des Samstags als ihren wöchentlichen Ruhetag. Und doch freuen sich die Gläubigen auf eine ewige Sabbatruhe (Hebr 4,1-13).

```


```{block, type='definition'}
**Werke -- Definition**

Handlungen und Einstellungen, entweder gut oder schlecht. Wahrer Glaube an Christus wird unweigerlich gute Werke hervorbringen, die Gott wohlgefällig sind. Gute Werke können niemals die Grundlage oder das Mittel zur Erlösung sein, die allein aus Gnade durch den Glauben erfolgt.
```

Lesen Sie die folgenden drei Abschnitte zu den Themen "Einblicke in das Evangelium", "biblische Zusammenhänge" und "theologische Vertiefungen". Nehmen Sie sich dann Zeit, über die persönlichen Auswirkungen nachzudenken, die diese Abschnitte auf Ihren Weg mit dem Herrn haben können.

## Einblicke in das Evangelium

**BEHARRLICHER GLAUBE.** Diejenigen, die beharrlichen Glauben zeigen, werden nicht im Unglauben abfallen (Hebräer 3,14). Die Selbstprüfung in Verbindung mit dem Glauben an das Evangelium bewahrt vor der Entwicklung eines verhärteten Herzens. Deshalb sollten wir wachsam sein und an unserem ursprünglichen Vertrauen in das Evangelium Jesu Christi bis zum Ende festhalten und Gottes Wort dazu benutzen, jeglichen Unglauben oder Ungehorsam zu offenbaren (Hebräer 3,12-13). Beharrlichkeit im Glauben ist ein Mittel der Sicherheit, die Gläubige im christlichen Leben haben (Hebräer 3,6). Glücklicherweise ist es die Gnade Gottes, die uns rettet und bis zum Ende erhält.

**SABBATS RUHE.** Im Evangelium gibt Gott seinem Volk die Sabbatruhe (Hebräer 4,9-10). Im Schöpfungsbericht lesen wir, dass Gott am siebten Tag ruhte, weil sein Werk vollendet war (1. Mose 2,2). Die Menschheit ahmt das Muster von Gottes Werk und Ruhe im Sabbatzyklus nach (Ex 20,8-11; Levitikus 25). Der Sabbat weist nach vorn auf die Ruhe, die Christus mit seiner Auferstehung und Himmelfahrt erreicht hat (Hebräer 10,12-13). Christen treten in eine tiefe Ruhe der Seele ein, wenn sie bekennen, dass das Erlösungswerk Jesu vollendet war, als er erklärte: "Es ist vollbracht", und dann, als er von den Toten auferstand (Johannes 19,30; 20,19). Die Kirche wartet nun auf Jesu zweites Kommen, bei dem sich Gottes Ruhe vollständig offenbaren wird (Offenbarung 22,3-5). Bis zu diesem Tag sind die Gläubigen aufgerufen, in Christi Erlösung zu ruhen und der Versuchung zu widerstehen, in die Gerechtigkeit der Werke zurückzufallen (Galater 2,16; 3,10-14).

## Biblische Zusammenhänge

**TREUER KNECHT.** Mose erfüllte treu die von Gott festgelegten Aufgaben als Befreier aus der Sklaverei in Ägypten, als Führer des Exodus und als Gesetzgeber (2. Mose 3,10; 5. Mose 18,15-19). Jesus ist insofern grösser als Mose, als er sein Volk aus der grösseren Sklaverei von Sünde und Tod befreit und in die verheissene ewige Ruhe Gottes führt.

**DEN SOHN DES MENSCHEN.** Der Titel, den Jesus mehr als jeder andere verwendet, um sich auf sich selbst zu beziehen, ist "der Menschensohn" (z.B. Matthäus 8,20; 11,19). Obwohl diese Bezeichnung die Menschlichkeit Jesu unterstreichen mag, ist der Ausdruck am wichtigsten in Bezug auf die Gestalt in Daniel 7, die von Gott die höchste Autorität und ein ewiges Königreich erhält (siehe Daniel 7,13-14; Matthäus 26,64; Markus 14,62). Und als der vollkommene Sohn hält Jesus treu die Gesamtheit des Gesetzes aufrecht und befähigt ihn, als Hoherpriester und ewiger König zu dienen (Hebräer 3,1-6).

**EXODUS ZUR VERHEISSUNG.** Das Volk der Exodus-Generation konnte aufgrund seines Unglaubens und Ungehorsams nicht in den Rest Gottes (das verheissene Land) einziehen (Num. 14,20-24; 20,12). Das Muster des Exodus wiederholt sich in der Befreiung der Kirche von Sünde und Tod und in ihrer zukünftigen Befreiung von der verheissenen ewigen Ruhe Gottes. Im Gegensatz zur Exodus-Generation ist Jesus der wahre Israelit, dessen Treue zu Gott vollkommen ist. Im Gegensatz zu Mose und Josua ist Jesus in der Lage, jeden einzelnen seines Volkes zu erhalten und der versprochenen Ruhe Gottes zu übergeben (Hebräer 4,1-16).

## Theologische Sondierungen

**HAUS GOTTES.** Wie andere Metaphern für das Volk Gottes bezieht sich "Haus" auf die gemeinsame Identität der Kirche als Gottes Wohnung (1. Korinther 3,16; 6,19; 2. Korinther 6,16; 1 Timotheus 3,15; 1 Petrus 2,5). Jesus hat als Sohn (Hebräer 3,6), als Baumeister (Hebräer 3,3-4) und als wichtigster Eckstein (Epheser 2,20-21) einen privilegierten Platz in Gottes Haus. Das Haus Gottes ist durch den Glauben geeint und aufgefordert, sich gegenseitig zu Glauben, Gehorsam und Ausdauer zu ermutigen.

**GOTTES WORT.** Die Bibel ist ein göttlich-menschliches Wort, das uns von Gott durch Menschen innerhalb der Erlösungsgeschichte gegeben wurde, die darüber Zeugnis ablegen, wer Gott ist und was er getan hat. Die Bibel ist Gottes persönliche Äusserung an uns, die als Gott selbst handelt, unsere Herzen sucht und offenbart. Durch Gottes geschriebenes Wort kann sein Volk Irrtümer aufdecken, in der Christusähnlichkeit wachsen und Verständnis dafür gewinnen, was es bedeutet, ein gottgefälliges Leben zu führen (Hebräer 4,12; 2. Timotheus 3,16).

## Persönliche Anwendung

Nehmen Sie sich Zeit, über die Auswirkungen von Hebräer 3,1-4,13 auf Ihr eigenes Leben nachzudenken. Beachten Sie die persönlichen Implikationen für Ihren Weg mit dem Herrn im Licht der (1) Einblicke in das Evangelium, (2) biblische Zusammenhänge, (3) theologischen Vertiefungen und (4) dieses Abschnitts als Ganzes.

1. Einblicke in das Evangelium
2. Biblische Zusammenhänge
3. Theologische Vertiefungen
4. Hebräer 3,1-4,13


## Wenn Sie diese Einheit abschliessen . . .

Nehmen Sie sich jetzt einen Moment Zeit, um um den Segen und die Hilfe des Herrn zu bitten, während Sie das Studium des Hebräerbriefes fortsetzen. Und nehmen Sie sich auch einen Moment Zeit, auf diese Studieneinheit zurückzublicken, über einige Dinge nachzudenken, die der Herr Sie vielleicht lehrt, und Dinge zu notieren, die Sie in Zukunft nachschauen sollten.


***

Nur für private Zwecke. Übersetzt aus dem Englischen von eurem Diener

Hebrews: A 12-Week Study $\copyright$ 2015 by Matthew Z. Capps. All rights reserved.

[source](https://www.thegospelcoalition.org/course/knowing-bible-hebrews/#week-4-jesus-is-superior-to-moses-heb-31-413)
