# Woche 5: Jesus ist der oberste Hohepriester, Teil 1 {#woche05}

```{block, type='biblebox'}
 **Lese Hebräer 4,14-5,10**
```

## Bedeutung des Abschnittes

Der Autor baut nun auf den Themen auf, die zuerst in Hebräer 2,17-3,12 eingeführt wurden. Er verkündet Jesus als den heiligen und mitfühlenden Hohenpriester, der von Gott dem Vater ernannt wurde. Darüber hinaus soll Christus um der anderen willen leiden, damit sie die Gabe der ewigen Errettung empfangen können (Hebräer 4,14-5,10). Treue ist die angemessene Antwort auf alles, was Christus für uns getan hat.


## Das Gesamtbild

In Hebräer 4,14-5,10 wird Jesus Christus, der sündlose Sohn Gottes, als der ernannte mitfühlende Hohepriester nach der Ordnung Melchisedeks gepriesen.

## Reflexion und Diskussion

Lesen Sie den Studienabschnitt, Hebräer 4,14-5,10, durch. Nachdem Sie den Abschnitt gelesen haben, lesen Sie den Abschnitt wieder und halten Sie Ihre eigenen Antworten auf die folgenden Fragen fest. 

### Jesus, der grosse Hohepriester (Hebr. 4,14-5,10)

Der Autor kündigte Jesu Rolle als Hohepriester in Hebräer 2,17 an; hier in Hebräer 4,14-16 wird Jesu Rolle als Hohepriester näher erläutert. Jesus ist "durch die Himmel gegangen" und sitzt nun zur Rechten Gottes (Hebräer 1,13; 4,14). Unser grosser Hohepriester ist nicht nur der göttliche Sohn-Gott selbst - er ist auch ganz Mensch und in der Lage, mit uns zu sympathisieren (Hebräer 4,15). In welch einzigartiger Weise kann Jesus mit uns mitfühlen, da er sowohl mit dem Himmel als auch mit der Erde eng vertraut ist?

Nach diesem Abschnitt muss der Hohepriester von Gott in sein Amt berufen werden und in der Lage sein, mit denen, die er vertritt, zu sympathisieren. Wie befähigt uns das Wissen, dass Jesus unser grosser Hohepriester ist, an unserem Glauben festzuhalten?

Der Autor ermahnt den Leser, sich vertrauensvoll dem Thron der Gnade zu nähern, um Barmherzigkeit und Hilfe in Zeiten der Not zu finden (Hebräer 4,16). Obwohl wir immer noch mit der innewohnenden Sünde kämpfen, wird Gottes heiliger Thron durch Christus zu einem Thron der Gnade. Wie gibt uns das Ansporn zu Gebet und Lobpreis? Warum sind Christen in der Lage, ehrlich vor Gott zu reden, ohne Angst vor Verdammnis?

Hohe Priester erhalten ihren Berufung und ihre Aufgabe von Gott dem Allmächtigen. Was ist nach Hebräer 5,1-2 die wesentliche Aufgabe des Hohepriesters? In welcher Weise erfüllen Leben und Werk Jesu die hohepriesterlichen Kriterien (Hebräer 5,1-2.5)? Inwiefern unterscheidet sich Jesus von früheren Hohepriestern und ist grösser als sie (Hebräer 5,3)?
In Hebräer 5,5-6 weist der Verfasser noch einmal auf Psalm 2,7 und Psalm 110 hin, um von Christus als dem Sohn und ewigen Hohepriester in der Ordnung Melchisedeks zu sprechen. Warum wird Jesus mit Melchisedek verglichen (1. Mose 14,18-20)?

Während seines Erdenlebens hat Jesus mit lautem Schreien und unter Tränen intensive, herzliche, ehrfürchtige und unterwürfige Gebete zu Gott, dem Vater, gesprochen (Hebräer 5,7; siehe z.B. Lukas 22,39-46). Der vollkommene Gehorsam Jesu bildete die Grundlage dafür, dass seine Gebete erhört wurden (Hebräer 5,8). Wie können wir in Zeiten des Kampfes von Christi vollkommenem Gebetsleben lernen und, was noch wichtiger ist, uns auf dieses stützen?

In Hebräer 5,8-9 wird erklärt, dass Jesus durch das, was er erlitt, Gehorsam lernte und dadurch vollkommen wurde. Im Wesentlichen wurde Jesus in dem Sinne "vollkommen gemacht", dass er durch seinen vollkommenen Gehorsam qualifiziert wurde, allen Gläubigen die Quelle der Erlösung zu sein (Hebräer 5,9). Wie kann uns die Erfahrung und Vollkommenheit Jesu Hoffnung geben, wenn uns der von Gott gewollte Gehorsam fehlt?


```{block, type='definition'}
**Barmherzigkeit -- Definition**

Mitgefühl und Freundlichkeit gegenüber jemandem, der Not leidet, manchmal sogar dann, wenn dieses Leiden auf die eigene Sünde oder Dummheit zurückzuführen ist. Gott zeigt Barmherzigkeit gegenüber seinem Volk, und dieses wiederum ist aufgerufen, Barmherzigkeit gegenüber anderen zu zeigen (Lukas 6,36).
```


```{block, type='definition'}
**Priest -- Definition**

Im alttestamentlichen Israel vertrat der Priester das Volk vor Gott und vertrat Gott vor dem Volk. Nur diejenigen, die von Aaron abstammten, konnten Priester sein. Zu ihren vorgeschriebenen Aufgaben gehörten auch die Inspektion und Entgegennahme von Opfern aus dem Volk und die Überwachung der täglichen Aktivitäten und der Instandhaltung der Stiftshütte oder des Tempels.
```

Lesen Sie die folgenden drei Abschnitte zu den Themen "Einblicke in das Evangelium", "biblische Zusammenhänge" und "theologische Vertiefungen". Nehmen Sie sich dann Zeit, über die persönlichen Auswirkungen nachzudenken, die diese Abschnitte auf Ihren Weg mit dem Herrn haben können.

## Einblicke in das Evangelium

**VERSUCHUNG OHNE SÜNDE.** Die Versuchung kann als die Absicht gesehen werden, uns zu Fall zu bringen, oder sie kann als Prüfung angesehen werden, um uns in der Heiligung aufzubauen (Matthäus 4,1-11; Lukas 22,28). Jesus wurde in jedem Bereich des Lebens versucht, doch im Gegensatz zu jedem anderen Menschen blieb er frei von Sünde. Christen können Trost darin finden, dass Jesus in der Versuchung mit ihnen mitfühlen kann, und im Wissen, dass Jesus vollkommen treu und gehorsam blieb, wo sie sich der Sünde hingeben (Hebräer 4,15). Wichtiger noch: Wenn wir der Versuchung nachgeben, werden wir von Gott nicht endgültig verurteilt. Der vollkommene Gehorsam Christi ist uns zugeschrieben worden, und wir werden durch seinen Geist zur Busse gezogen werden, und durch seine Gnade wird uns vergeben werden.

**THRON DER GNADE.** Ein Thron ist ein Sinnbild für Autorität, Majestät und Macht. Der Thron Gottes ist ein heiliger Thron (Psalm 47,8) und ist ein Ort des Gerichts und der Verurteilung der Sünde. Aufgrund des vollendeten Werkes Christi am Kreuz sind Christen jedoch aufgerufen, sich mutig dem Thron Gottes zu nähern. Da Jesus zu seiner Rechten sitzt (Hebräer 4,16; 8,1; 12,2) und für die Heiligen Fürbitte einlegt (Hebräer 7,25; 10,22), sorgt Gott der Vater gnädig für die Vergebung der Sünden und gibt den Christen Kraft, die Versuchung zu überwinden (Hebräer 2,18). In Demut und Zuversicht können wir unsere Sünde bekennen und wissen, dass Gott uns vergeben und uns Gnade erweisen wird.

**EWIGE ERRETTUNG.** Der vollkommene Gehorsam (Hebräer 5,8; 7,26-28) und das Opfer Jesu bilden die Grundlage für die Errettung aus Gnade durch den Glauben. Die Errettung durch Christus ist ewig (Hebräer 2,10; 9,23-28), weil das Opfer Jesu ein für allemal gebracht wurde (Hebräer 10,12). Als Gläubige werden wir von Christus gehalten und mit dem Geist versiegelt bis zum letzten Tag (Johannes 10:28; 2. Korinther 1:22). Am letzten Tag wird Christus die Seinen beanspruchen vor dem Vater im Himmel (Offenbarung 3:5).

## Biblische Zusammenhänge

**HOHEPRIESTER.** Im mosaischen Priestertum diente der levitische Hohepriester als religiöses Oberhaupt seines Volkes und Mittler zwischen Gott und Mensch. Der Hohepriester war der einzige, dem es erlaubt war, den inneren Teil des Tempels zu betreten, in dem Gott wohnte, um für sein Volk Sühne zu leisten (2. Mose 26,33; 3. Mose 16). Indem er das vollkommene Opfer für die Sünde darbrachte, öffnete der wahre und grössere Hohepriester Jesus dem ganzen Volk Gottes den Weg, um in die Fülle der Gegenwart Gottes einzutreten (Hebräer 7,27). Während die levitischen Priester vorübergehend waren, dient Jesus als ständiger und ewiger Hohepriester (Hebräer 7:23-24). Aufgrund des Wirkens Christi können wir uns Gott immer vertrauensvoll nähern (Hebräer 4,14-16).

**MELCHISEDEK.** Melchisedek war zur Zeit Abrahams ein "König-Priester"-König von Salem und Priester Gottes (1. Mose 14:17-20; Psalm 110:4). Melchisedek dient als ein Typus für Jesus als König-Priester. Melchisedeks Name wird als "König der Gerechtigkeit" und sein Titel als König von Salem als "König des Friedens" interpretiert, was Jesu Herrschaft von Gerechtigkeit und Frieden vorwegnimmt (Hebräer 7:1-10).

## Theologische Sondierungen

**JESUS BEGRENZUNGEN.** Die Menschlichkeit des Gottessohnes brachte ihm gewisse Begrenzungen. Er wurde als hilfloser Säugling geboren und wuchs ins Erwachsenenalter hinein, genau wie wir anderen auch (Lukas 2,7; 2,40.52). Er wurde müde und hungrig, wie alle Menschen (Johannes 4,6; 19,28; Matthäus 4,2). Jesus hatte auch die ganze Bandbreite menschlicher Gefühle. Vor seiner Kreuzigung, als er sich der Realität stellte, für die Sünden der Menschheit abgeschlachtet zu werden, war seine Seele traurig, sogar bis zum Tod (Matthäus 26,38). Sein Herz war oft voller Emotionen, wenn er zum Vater betete (Hebräer 5,7). Jesus gewann während seines ganzen Lebens an moralischer Stärke, als er das Werk vollendete, zu dessen Vollendung sein Vater ihn gesandt hatte. Bei all dem blieb er ohne Sünde (Hebräer 4,15; 5,8).

**PERSÖNLICHER GOTT.** Der Gott der Bibel ist keine abstrakte Gottheit, die von seiner Schöpfung entfernt ist; er ist ein persönlicher Gott, der sich auf seine Schöpfung bezieht und mit seinem Volk sympathisiert. Dies zeigt sich am deutlichsten in der Inkarnation Jesu Christi. In Hebräer 4,15-16 werden wir daran erinnert, dass die Menschlichkeit Jesu ihn auch befähigt, mit uns als unserem Hohenpriester zu sympathisieren. Aufgrund seiner Menschlichkeit ist Jesus in der Lage, die Versuchungen und Kämpfe unseres Lebens durch Erfahrung zu erkennen, und kann daher mit uns mitfühlen und uns helfen, wenn wir in Versuchung geraten (Hebräer 2,18). Jesus ist nun in die Gegenwart Gottes eingetreten, und durch seine Gegenwart dort bittet er in unserem Namen (Hebräer 9,24-28).


## Persönliche Anwendung

Nehmen Sie sich Zeit, über die Auswirkungen von Hebräer 4,14-5,10 auf Ihr eigenes Leben nachzudenken. Beachten Sie die persönlichen Implikationen für Ihren Weg mit dem Herrn im Licht der (1) Einblicke in das Evangelium, (2) biblische Zusammenhänge, (3) theologischen Vertiefungen und (4) dieses Abschnitts als Ganzes.

1. Einblicke in das Evangelium
2. Biblische Zusammenhänge
3. Theologische Vertiefungen
4. Hebräer 4,14-5,10


## Wenn Sie diese Einheit abschliessen . . .

Nehmen Sie sich jetzt einen Moment Zeit, um um den Segen und die Hilfe des Herrn zu bitten, während Sie das Studium des Hebräerbriefes fortsetzen. Und nehmen Sie sich auch einen Moment Zeit, auf diese Studieneinheit zurückzublicken, über einige Dinge nachzudenken, die der Herr Sie vielleicht lehrt, und Dinge zu notieren, die Sie in Zukunft nachschauen sollten.


***

Nur für private Zwecke. Übersetzt aus dem Englischen von eurem Diener

Hebrews: A 12-Week Study $\copyright$ 2015 by Matthew Z. Capps. All rights reserved.

[source](https://www.thegospelcoalition.org/course/knowing-bible-hebrews/#week-5-jesus-is-the-superior-high-priest-part-1-heb-414-510)
