# Woche 6: Eine Warnung vor dem Glaubensabfall {#woche06}

```{block, type='biblebox'}
 **Lese Hebräer 5,11-6,20**
```


## Bedeutung des Abschnittes

Der Autor unterbricht die Darlegung der Rolle Jesu als Hoherpriester (Hebräer 4,14-5,10; 7,1-8,13) und fordert die Leser plötzlich auf, über die Grundlagen des Glaubens hinaus zur geistlichen Reife zu gelangen (Hebräer 5,11-6,3). Abschliessend ermahnt er sie und zeigt Vertrauen in ihre Fähigkeit zur Ausdauer, indem er Abraham als Beispiel für "treuen Glauben" anführt (Hebräer 6,9-20). Die dritte von fünf warnenden Passagen erscheint in Hebräer 6,4-8 und warnt die Leser vor der Gefahr des Abfalls.


## Das Gesamtbild

Hebräer 5,11-6,20 verherrlicht Gott, indem er auf Jesus Christus als den Vorläufer, Anker und Hohenpriester unseres Glaubens hinweist.

## Reflexion und Diskussion

Lesen Sie den Studienabschnitt, Hebräer 4,14-5,10, durch. Nachdem Sie den Abschnitt gelesen haben, lesen Sie den Abschnitt wieder und halten Sie Ihre eigenen Antworten auf die folgenden Fragen fest. 

### 1. Warnung Drei: Gegen den Glaubensabfall (Hebräer 5,11-6,12)

In Hebräer 5,11-12 schilt der Autor die Leser für ihre Unreife im Glauben, denn, so sagt er, sie seien "schwerhörig" geworden (Hebräer 5,11) und hätten kein solides Verständnis der grundlegenden Wahrheiten Gottes (Hebräer 5,12). Was sind einige mögliche Gründe für ihre geistige Faulheit und ihre mangelnde Bereitschaft, die tieferen Implikationen des Evangeliums in ihrem Leben herauszuarbeiten?

An diesem Punkt ihres Glaubens sollte die ursprüngliche Zuhörerschaft reif genug sein, um andere in "den Grundprinzipien der Orakel Gottes" zu unterweisen, die er auch als "Wort der Gerechtigkeit" bezeichnet (Hebräer 5,12-13). Worauf weist der Autor mit "Grundprinzipien" und grundlegenden "Orakeln" Gottes hin (siehe Hebräer 6,1-2; Apostelgeschichte 7,38; Römer 3,2)?

Im Vergleich zu denen, die im Glauben noch Kinder sind, wird der reife Gläubige als gut gelernt und gut praktiziert im Glauben charakterisiert (Hebräer 5,14). Warum sind sowohl Lehre als auch Praxis für die Reifung eines Gläubigen wichtig?

Der Autor weist darauf hin, dass er sich dafür einsetzt, die Leser von der Unreife zur Glaubensreife zu führen (Hebräer 6:3). In Hebräer 6,1-2 sehen wir drei Paare von Grundprinzipien:

1. Glaube und Busse: Die Umkehr von der Sünde und die Umkehr vom Vertrauen auf die eigenen Werke zur Ruhe auf dem vollendeten Werk Christi sind die Kennzeichen der christlichen Bekehrung (Hebräer 6,12; 9,14; 10,22.38-39; 12,2; 13,7).
2. Waschen und Handauflegen: Diese charakteristischen Initiationsriten zeigen an, dass man ein aktiver Teil der Kirche wird (Apostelgeschichte 6,6; 8,14-17; 9,12-19; 19,5-6).
3. Auferstehung und ewiges Gericht: Christen haben eine Zukunftshoffnung in der Auferstehung. Sie sind in Christus sicher vor dem ewigen Gericht, das auf Nichtchristen wartet (Hebräer 9,27; 10,27; 11,19.35).

Warum sind diese Prinzipien wichtig, um jemandem auf dem Weg zur Glaubensreife zu helfen?

In Hebräer 6,4-7 stellt der Verfasser fest, dass einige der ursprünglichen Zuhörer an der christlichen Kirche teilgenommen und an ihren Segnungen teilgenommen haben, aber entweder Gefahr laufen, zu fallen, oder bereits vom Glauben abgefallen sind (es ist nicht klar, was er meint). Darüber hinaus sagt er, dass es unmöglich ist, solche Menschen wieder zur Umkehr zu bringen, weil sie Christus absichtlich ablehnen. Beschreiben Sie, was der Autor meint, wenn er diejenigen, die "abgefallen" sind, beschuldigt, Christus zu verachten und ihn in den Augen anderer verächtlich zu machen (Hebräer 6,6-7).

Ist es möglich, durch Gottes Wort über die Erlösung erleuchtet zu werden, den Anschein zu erwecken, dass man geistgewirkte Reue über die Sünde zeigt und sogar Zeichen der Bekehrung zeigt, und trotzdem im Glauben nicht standhaft bleibt (Hebräer 6,4-6)? Warum ist es unmöglich, solche Menschen zur Umkehr zu bewegen (Hebräer 6,6-7)?

Der Autor verwendet die landwirtschaftliche Illustration in Hebräer 6:7, damit die Leser seinem Aufruf zu Ausdauer und Geduld folgen (Hebräer 6:11-12). Wie entfacht der Glaube an die Errettung und ein Leben im Dienst am Nächsten (Hebräer 6,10-11) Ausdauer und Hoffnung auf die Verheissungen Gottes? Was sind die besseren Dinge, die die Erlösung begleiten (Hebräer 6,9)?

### 2. Die Gewissheit von Gottes Verheissung (Hebräer 6,13-20)

In Hebräer 6,13-15 gibt der Schriftsteller Abraham als Beispiel für einen, der durch Geduld und Glauben die Verheissungen Gottes erbte (1. Mose 22,16-17). Auf welche Weise ermutigt dieser Abschnitt die Gläubigen, Abrahams Geduld nachzuahmen, wenn es darum geht, die Verheissung Gottes zu erben?

In der Antike erforderten Eide einen Appell an eine höhere Autorität. In diesem Abschnitt heisst es, dass Gott seine Verheissung mit einem Eid geschworen hat, um seine Vertrauenswürdigkeit zu bestätigen (Hebräer 6,16-18). Auf welche Weise erzeugt dies beim Leser Hoffnung und Vertrauen, dass er an Gottes Wort festhält?

Während der Autor die Leser vor einem Abfall vom Glauben warnt, verankert er auch ihre Heilsgewissheit in Jesus Christus (Hebräer 6,19-20). Welche Bedeutung haben die alttestamentlichen Hinweise in diesem Abschnitt für die Festigung Jesu als Manifestation der Hoffnung für das Volk Gottes (Matthäus 27,51; Hebräer 9,3; 10,20)?


```{block, type='definition'}
**Busse -- Definition**

Ein völliger Sinneswandel in Bezug auf die allgemeine Einstellung zu Gott und/oder die eigenen Handlungen. Wahre Regeneration und Bekehrung geht immer mit Busse einher.
```


```{block, type='definition'}
**Eid -- Definition**

Das Volk Gottes wurde im Alten Testament davor gewarnt, Versprechen unüberlegt oder falsch zu schwören (3. Mose 5,4; 19,11-12). Manchmal wurden Eide in Gottes Namen geschworen, als ob sie eine Garantie dafür sein sollten, aber Jesus sagte seinen Jüngern, überhaupt keine Eide zu schwören. Vielmehr sollten sie ihre einfache Aussage "ja" ja und ihr "nein" nein bedeuten lassen (Matthäus 5,33-37). Gottes eigener Eid ist jedoch eine endgültige und unanfechtbare Garantie (Hebräer 6,13-20).
```

Lesen Sie die folgenden drei Abschnitte zu den Themen "Einblicke in das Evangelium", "biblische Zusammenhänge" und "theologische Vertiefungen". Nehmen Sie sich dann Zeit, über die persönlichen Auswirkungen nachzudenken, die diese Abschnitte auf Ihren Weg mit dem Herrn haben können.

## Einblicke in das Evangelium

**IN CHRISTUS ALLEIN.** Es ist unmöglich, jemanden zur Busse zu führen, wenn er oder sie weiterhin das Evangelium ablehnt. Diejenigen, die Christus ablehnen, haben sich von der einzigen Grundlage abgewandt, auf der die Hoffnung auf Erlösung ausgedehnt werden kann (Matthäus 12,31-32; Hebräer 6,4). Diejenigen, die auf diese Weise apostasisch werden, verachten Jesus, und indem sie ihn ablehnen, versetzen sie sich in die Lage derer, die ihn gekreuzigt haben. Mit anderen Worten: Abtrünnige lassen die Schande des Kreuzes nachwirken (Hebräer 6,6). Während wir alle wegen unserer Sündhaftigkeit vor Gericht und Verurteilung stehen, steht uns durch die Gnade Gottes die Erlösung in Christus - und nur in ihm - zur Verfügung.

**ERLÖSUNGS-EID GOTTES.** In der Antike bestand der Hauptzweck eines Eides darin, das Gesagte zu bestätigen und damit allen Streitigkeiten ein Ende zu setzen (Hebräer 6,16-18); diejenigen, die Eide ablegten, waren dem Gericht ausgesetzt, wenn sie sie brachen (5. Mose 23,21-23). Gott schwor Abraham von sich aus einen Eid bezüglich der Erben seiner Verheissung (Hebräer 6,13; 1. Mose 15). Daher ist die Verheissung der Errettung durch das Hohepriestertum Jesu überaus vertrauenswürdig (Hebräer 6,19-20). Gottes Heilsplan ist unveränderlich. Dementsprechend haben Gläubige den stärksten Grund, an Gottes Wort der Errettung festzuhalten.

## Biblische Zusammenhänge

**ABRAHAMS VERSPRECHEN.** Gott versprach Abraham zahllose Nachkommen (Hebräer 2,16; 1. Mose 12,1-3; 17,4-21; 18,17-19). Erst ein Vierteljahrhundert später wurde Isaak geboren (1. Mose 21,1-7). Jede Hoffnung auf Erfüllung der Verheissung, die Gott Abraham in Bezug auf seine Nachkommen gegeben hatte, hing an Isaak, und es war Isaak, dem Abraham befohlen wurde, ihn als Opfer zu opfern - obwohl ihm schliesslich ein Widder an seiner Stelle zur Verfügung gestellt wurde. Die volle Verwirklichung der Verheissung fand sich in Jesus, dem Nachkommen, der als Opfer dargebracht werden sollte, um die Errettung für Abrahams Nachkommen zu sichern und so alle Nationen der Erde zu segnen (1. Mose 22,16-18).

**WEGFALLEN.** Die Beschreibung des Abfallens in Hebräer 6,4-6 erinnert an den Kontext der Reise Israels durch die Wüste und des Mangels an Ausdauer. Israel erfuhr die göttliche Gabe der Versorgung Gottes durch Manna in der Wüste (1. Mose 16,4); dennoch gelang es ihm wegen seines Unglaubens nicht, das verheissene Land zu betreten. In ähnlicher Weise haben viele die Segnungen des neuen Bundes erfahren, doch geistlich gesehen "kehren sie nach Ägypten zurück" und büssen die ewige Ruhe ein. Seien Sie gewarnt: Diejenigen, die schliesslich abfallen, mögen viele äussere Zeichen des Glaubens geben, bevor sie Christus verlassen (Hebräer 6,7-8). Von Gott "abzufallen" führt zu Tod und ewigem Gericht (Hebräer 3,12; 12,15).


## Theologische Sondierungen

**SUFFIZIENZ DER SCHRIFT.** Die Bibel ist ausreichend und nützlich für die Lehre, die für ein gottgefälliges Leben erforderlich ist (Psalm 19,7-9; 2. Timotheus 3,16-17). Die Leser, an die sich Hebräer 5,11-14 wendet, sind wegen ihrer Faulheit und mangelnden Bereitschaft, die tieferen Implikationen von Gottes Wort in ihrem Leben herauszuarbeiten, in der Lehre noch Kinder. Das Ziel des Autors ist es jedoch, dass die Leser durch die Entwicklung der Lehre und durch Beispiele aus der Schrift zur Reife gelangen (Hebräer 6,1-12).

**UNVERZEIHLICHE SÜNDE.** In den Evangelienberichten spricht Jesus von der unverzeihlichen Sünde, nämlich der Gotteslästerung gegen den Heiligen Geist (Matthäus 12,31-32; Markus 3,29; Lukas 12,10). In Hebräer 6,4-6 spricht der Autor von denen, die die Überzeugung von der Wahrheit erfahren und die Güte Gottes gekostet haben und sich dennoch willentlich von Jesus abwenden. Während sie von der Wahrheit des Evangeliums überzeugt sind, widersetzen sie sich ständig und vorsätzlich dem Wirken des Heiligen Geistes, der dieses Evangelium bezeugt (vgl. Hebräer 10,26-27).

```{block, type='definition'}
**Der Heilige Geist -- Definition**


Eine der Personen der Dreieinigkeit, ganz Gott. Die Bibel erwähnt mehrere Rollen des Heiligen Geistes, darunter die, Menschen von der Sünde zu überführen, sie zur Umkehr zu bringen, ihnen einzuwohnen und sie zu befähigen, in Rechtschaffenheit und Treue zu leben, sie in Zeiten der Prüfung zu unterstützen und ihnen das Verständnis der Heiligen Schrift zu ermöglichen. Der Heilige Geist inspirierte die Schreiber der Heiligen Schrift und führte sie dazu, die Worte Gottes selbst aufzuzeichnen. Der Heilige Geist war im Leben und Wirken Jesu auf Erden besonders aktiv (z.B. Lukas 3,22).
```


## Persönliche Anwendung

Nehmen Sie sich Zeit, über die Auswirkungen von Hebräer 5,11-6,20 auf Ihr eigenes Leben nachzudenken. Beachten Sie die persönlichen Implikationen für Ihren Weg mit dem Herrn im Licht der (1) Einblicke in das Evangelium, (2) biblische Zusammenhänge, (3) theologischen Vertiefungen und (4) dieses Abschnitts als Ganzes.

1. Einblicke in das Evangelium
2. Biblische Zusammenhänge
3. Theologische Vertiefungen
4. Hebräer 5,11-6,20


## Wenn Sie diese Einheit abschliessen . . .

Nehmen Sie sich jetzt einen Moment Zeit, um um den Segen und die Hilfe des Herrn zu bitten, während Sie das Studium des Hebräerbriefes fortsetzen. Und nehmen Sie sich auch einen Moment Zeit, auf diese Studieneinheit zurückzublicken, über einige Dinge nachzudenken, die der Herr Sie vielleicht lehrt, und Dinge zu notieren, die Sie in Zukunft nachschauen sollten.


***

Nur für private Zwecke. Übersetzt aus dem Englischen von eurem Diener

Hebrews: A 12-Week Study $\copyright$ 2015 by Matthew Z. Capps. All rights reserved.

[source](https://www.thegospelcoalition.org/course/knowing-bible-hebrews/#week-6-a-warning-against-apostasy-heb-511-620)
