--- 
title: "Die Bibel kennen: Hebräerbrief"
author: ""
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
theme: cerulean
documentclass: krantz
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: bibelstudy/hebraeerbrief
description: "Hebräerbrief - Eine 12-wöchige praktische Studienreihe"
---

# Studienplan

Eine 12-wöchige praktische Studienreihe über den Hebräerbrief
von Matthew Z. Capps [(Quelle auf English)](https://www.thegospelcoalition.org/course/knowing-bible-hebrews).

Übersetzt aus dem Englischen von eurem Diener.





* [Woche 1: Übersicht](#woche01)
* [Woche 2: Einführung: Die Vormachtstellung Jesu Christi (Hebräer 1,1-4)](#woche02)
* [Woche 3: Jesus ist den Engelswesen überlegen (Hebräer 1,5-2,18)](#woche03)
* [Woche 4: Jesus ist Mose überlegen (Hebräer 3,1-4,13)](#woche04)
* [Woche 5: Jesus ist der oberste Hohepriester, Teil 1 (Hebräer 4,14-5,10)](#woche05)
* [Woche 6: Eine Warnung vor dem Glaubensabfall (Hebräer 5,11-6,20)](#woche06)
* Woche 7: Jesus ist der oberste Hohepriester, Teil 2 (Hebräer 7,1-8,13)
* Woche 8: Jesus ist das überlegene Opfer (Hebräer 9,1-10,18)
* Woche 9: Der Ruf zum Glauben (Hebräer 10,19-11,40)
* Woche 10: Der Ruf zur Ausdauer (Hebräer 12,1-29)
* Woche 11: Letzte Ermahnungen (Hebräer 13,1-25)
* Woche 12: Zusammenfassung und Schlussfolgerung



```{block, type='infobox'}
**Soli Deo Gloria**
```

***

Nur für private Zwecke.

Hebrews: A 12-Week Study © 2015 by Matthew Z. Capps. All rights reserved.

https://www.thegospelcoalition.org/course/knowing-bible-hebrews/#week-1-overview
